export enum ChartCode {
  PEOPLE_CONNECTED = 1,
  INSTALLED_RENEWABLE,
  INVESTMENTS,
  COMMUNITIES_CONNECTED,
  ELECTRICITY_CONSUMED,
  AVERAGE_TARIFF,
  CONNECTIONS,
  EMPLOYMENTS,
  NEW_SERVICES,
  CUSTOMER_SATISFACTION,
  INSTALLED_CAPACITY,
  AVERAGE_CONSUMPTIONS,
  CAPACITY_UTILIZATION,
  ELECTRICITY_CONSUMPTION,
  REVENUE,
  CAPEX,
  OPEX,
  FINANCING_STRUCTURE,
}

export enum ChartType {
  OVERVIEW = 1,
  ADVANCED_ANALYTICS,
}

export enum ConvertableType {
  UNIT = 1,
  CURRENCY,
}
